site_name: Kotlinmailer
site_description: A simple, modern and coroutine based Kotlin Email API for clientside projects
site_author: David Bieregger

theme:
  name: material
  language: en
  favicon: img/logo.png
  icon:
    repo: fontawesome/brands/github
  logo: img/logo.png
  palette:
    scheme: preference
    primary: black
    accent: black

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 4

repo_url: https://github.com/BierDav/Kotinmailer/
repo_name: BierDav/Kotinmailer

edit_uri: edit/main/guide/docs/

nav:
  - Home: index.md
  - Setup:
      - Setup using Gradle: setup_gradle.md
      - Setup using Maven: setup_maven.md
  - Core:
      - Mailer API: mailer.md
      - Email API: email.md
      - Kotlin HTML DSL: html.md
      - Convert: convert.md
  - TLS: tls.md
