name: Publish package to Maven Central
on:
  workflow_call:
    inputs:
      version:
        description: 'Version'
        type: string
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup gradle.properties
        run: |
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_TOKEN }}" >> gradle.properties
          echo "customSigningInMemoryKey=${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}" >> gradle.properties
          echo "customSigningInMemoryKeyPassword=${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY_PASSWORD }}" >> gradle.properties

      - name: Publish artifact
        run: |
          chmod +x gradlew
          ./gradlew publish
          

