name: Publish package to the Maven Central Repository
on:
  release:
    types: [ created ]
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: ${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}}
      - name: Publish artifact
        run: ./gradlew publish --info --scan --debug -Psigning.gnupg.keyName=${{secrets.OSSRH_GPG_SECRET_KEY_ID}} -Psigning.gnupg.passphrase=${{secrets.OSSRH_GPG_SECRET_KEY_PASSWORD}} -Psigning.gnupg.optionsFile=${GITHUB_WORKSPACE}/gpg.conf
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_USERNAME}}
          MAVEN_PASSWORD: ${{secrets.OSSRH_TOKEN}}